qcacld-3.0: fix sizeof-pointer-div warnings
In file included from ../drivers/staging/qcacld-3.0/core/cds/inc/cds_api.h:37,
                 from ../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:37:
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c: In function ‘cds_modify_pcl_based_on_enabled_channels’:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/inc/qdf_types.h:81:44: error: division ‘sizeof (uint8_t * {aka unsigned char *}) /
sizeof (uint8_t {aka unsigned char})’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
 #define QDF_ARRAY_SIZE(_arr) (sizeof(_arr) / sizeof((_arr)[0]))
                                            ^
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:5511:29: note: in expansion of macro ‘QDF_ARRAY_SIZE’
  qdf_mem_zero(pcl_list_org, QDF_ARRAY_SIZE(pcl_list_org));
                             ^~~~~~~~~~~~~~
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:5489:16: note: first ‘sizeof’ operand was declared here
       uint8_t *pcl_list_org,
       ~~~~~~~~~^~~~~~~~~~~~
In file included from ../drivers/staging/qcacld-3.0/core/cds/inc/cds_api.h:37,
                 from ../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:37:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/inc/qdf_types.h:81:44: error: division ‘sizeof (uint8_t * {aka unsigned char *}) /
sizeof (uint8_t {aka unsigned char})’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
 #define QDF_ARRAY_SIZE(_arr) (sizeof(_arr) / sizeof((_arr)[0]))
                                            ^
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:5512:32: note: in expansion of macro ‘QDF_ARRAY_SIZE’
  qdf_mem_zero(weight_list_org, QDF_ARRAY_SIZE(weight_list_org));
                                ^~~~~~~~~~~~~~
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:5490:16: note: first ‘sizeof’ operand was declared here
       uint8_t *weight_list_org,
       ~~~~~~~~~^~~~~~~~~~~~~~~
In file included from ../drivers/staging/qcacld-3.0/core/cds/inc/cds_api.h:37,
                 from ../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:37:
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c: In function ‘cds_modify_sap_pcl_based_on_mandatory_channel’:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/inc/qdf_types.h:81:44: error: division ‘sizeof (uint8_t * {aka unsigned char *}) /
sizeof (uint8_t {aka unsigned char})’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
 #define QDF_ARRAY_SIZE(_arr) (sizeof(_arr) / sizeof((_arr)[0]))
                                            ^
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:9846:29: note: in expansion of macro ‘QDF_ARRAY_SIZE’
  qdf_mem_zero(pcl_list_org, QDF_ARRAY_SIZE(pcl_list_org));
                             ^~~~~~~~~~~~~~
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:9803:67: note: first ‘sizeof’ operand was declared here
 QDF_STATUS cds_modify_sap_pcl_based_on_mandatory_channel(uint8_t *pcl_list_org,
                                                          ~~~~~~~~~^~~~~~~~~~~~
In file included from ../drivers/staging/qcacld-3.0/core/cds/inc/cds_api.h:37,
                 from ../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:37:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/inc/qdf_types.h:81:44: error: division ‘sizeof (uint8_t * {aka unsigned char *}) /
sizeof (uint8_t {aka unsigned char})’ does not compute the number of array elements [-Werror=sizeof-pointer-div]
 #define QDF_ARRAY_SIZE(_arr) (sizeof(_arr) / sizeof((_arr)[0]))
                                            ^
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:9847:32: note: in expansion of macro ‘QDF_ARRAY_SIZE’
  qdf_mem_zero(weight_list_org, QDF_ARRAY_SIZE(weight_list_org));
                                ^~~~~~~~~~~~~~
../drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c:9804:16: note: first ‘sizeof’ operand was declared here
       uint8_t *weight_list_org,
       ~~~~~~~~~^~~~~~~~~~~~~~~

 Conflicts:
	drivers/staging/qcacld-3.0/core/cds/src/cds_concurrency.c